// User action types
export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAIL = 'USER_LOG_IN_FAIL';
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
export const USER_LOG_OUT_FAIL = 'USER_LOG_OUT_FAIL';
export const USER_REGISTER_CHANGED = 'USER_REGISTER_CHANGED';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SET_CURRENT_USER = 'USER_SET_CURRENT_USER';
export const USER_UPDATE_SEARCH_INPUT = 'USER_UPDATE_SEARCH_INPUT';
export const USER_DISMISS_SEARCH_INPUT = 'USER_DISMISS_SEARCH_INPUT';

export const USERS_LOAD_USERS_LIST = 'USERS_LOAD_USERS_LIST';
